### ISSUE TITLE
Does this work with WS2812b?

### ISSUE THREAD

**Issue by wdebusschere** [vanshksingh/Pi5Neo#3]
We tried to use the library with a Raspberry pi 5, GPIO 10  and WS2812b with external power, but only 1 or 2 leds light up.. Has this been tested with WS2812b?
Thank you.

**Comment by vanshksingh** [comment]
Yes ! the led it has been tested with is [this](https://quartzcomponents.com/products/8-bit-ws2812-rgb-led-circular-development-board?_pos=3&_sid=ee2bfe322&_ss=r)

Also see [here](https://cdn.sparkfun.com/assets/learn_tutorials/1/0/5/WS2812B_VS_WS2812.pdf)

Have you connected the ground (from raspi) to the led too ? , it is needed for data transfer to work correctly almost everywhere , if you havent , **_try shorting the ground_** of your external power supply , and raspi and led 

**DONT SHORT THE +VE** 
_SHORT THE -VE_

**Comment by wdebusschere** [comment]
@vanshksingh Connecting the ground to the raspberry did the trick!  Thankyou.
