### ISSUE TITLE
Wiring examples

### ISSUE THREAD

**Issue by manfred-raab** [vanshksingh/Pi5Neo#4]
Dear Vansh Kumar;

This library sounds great, but could you give a short hint to the neccesary wiring. That would be very helpful.

Thanks in advance.

Manfred

**Comment by manfred-raab** [comment]
I find it out myself.

Neopixel 5V to PIN 2 (5V)
Neopixel GND to PIN 20 (GND)
Neopixel DI to PIN 19 (GPIO 10 / SPI0)

SPI ist not enabled by default. To turn it on via Desktop GUI use Raspberry Pi Configuration.

Via Terminal use raspi-config tool

**Comment by vanshksingh** [comment]
You can technically have 2 spi busses using default spidev 

And additionally an 3rd one using some config trick I saw somewhere
