### ISSUE TITLE
Can import pi5neo

### ISSUE THREAD

**Issue by mikecanann** [vanshksingh/Pi5Neo#6]
ImportError: cannot import name 'Pi5Neo' from partially initialized module 'pi5neo' (most likely due to a circular import) (/home/mikec/src/light_project/pi5neo.py)

**Comment by vanshksingh** [comment]
Are you able to use basic example ? And you installed it in your system on venv or on system with --break-system flag ?

**Comment by mikecanann** [comment]
I'm attempting to use the 10 line basic example. And I'm using venv

**Comment by mikecanann** [comment]
Tried that, still getting the issue:

$ python3 pi5neo.py 
Traceback (most recent call last):
  File "/home/mikec/src/pi5neo.py", line 2, in <module>
    from pi5neo import Pi5Neo
  File "/home/mikec/src/pi5neo.py", line 2, in <module>
    from pi5neo import Pi5Neo
ImportError: cannot import name 'Pi5Neo' from partially initialized module 'pi5neo' (most likely due to a circular import) (/home/mikec/src/pi5neo.py)


I also have the GPIO set to 10 (and configured and turned on in the OS), and the ground is also connected to the raspberry pi 5

**Comment by mikecanann** [comment]
By the way, I have this working with neopixel_spi. I can use the examples from that project and the lights work.

**Comment by vanshksingh** [comment]
Change your filename from pi5neo.py to something else 

`from pi5neo import Pi5Neo` here it trying to find the module from the script you are running itself thats why the issue

**Comment by mikecanann** [comment]
Thank you for your help!  And sorry for such a beginners mistake.
